package com.haha.im.model.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional uint64 fromId = 2;</code>
     */
    long getFromId();

    /**
     * <code>optional uint64 destId = 3;</code>
     */
    long getDestId();

    /**
     * <code>optional int64 createTime = 4;</code>
     */
    long getCreateTime();

    /**
     * <code>optional int32 step = 5;</code>
     */
    int getStep();

    /**
     * <code>optional bytes msgBody = 6;</code>
     */
    com.google.protobuf.ByteString getMsgBody();
  }
  /**
   * Protobuf type {@code ChatMsg}
   */
  public  static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatMsg)
      ChatMsgOrBuilder {
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      id_ = 0L;
      fromId_ = 0L;
      destId_ = 0L;
      createTime_ = 0L;
      step_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 16: {

              fromId_ = input.readUInt64();
              break;
            }
            case 24: {

              destId_ = input.readUInt64();
              break;
            }
            case 32: {

              createTime_ = input.readInt64();
              break;
            }
            case 40: {

              step_ = input.readInt32();
              break;
            }
            case 50: {

              msgBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_ChatMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.ChatMsg.class, Msg.ChatMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int FROMID_FIELD_NUMBER = 2;
    private long fromId_;
    /**
     * <code>optional uint64 fromId = 2;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int DESTID_FIELD_NUMBER = 3;
    private long destId_;
    /**
     * <code>optional uint64 destId = 3;</code>
     */
    public long getDestId() {
      return destId_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int STEP_FIELD_NUMBER = 5;
    private int step_;
    /**
     * <code>optional int32 step = 5;</code>
     */
    public int getStep() {
      return step_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>optional bytes msgBody = 6;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (fromId_ != 0L) {
        output.writeUInt64(2, fromId_);
      }
      if (destId_ != 0L) {
        output.writeUInt64(3, destId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(4, createTime_);
      }
      if (step_ != 0) {
        output.writeInt32(5, step_);
      }
      if (!msgBody_.isEmpty()) {
        output.writeBytes(6, msgBody_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fromId_);
      }
      if (destId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, destId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (step_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, step_);
      }
      if (!msgBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, msgBody_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Msg.ChatMsg)) {
        return super.equals(obj);
      }
      Msg.ChatMsg other = (Msg.ChatMsg) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getFromId()
          == other.getFromId());
      result = result && (getDestId()
          == other.getDestId());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getStep()
          == other.getStep());
      result = result && getMsgBody()
          .equals(other.getMsgBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDestId());
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStep();
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Msg.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Msg.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMsg)
        Msg.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_ChatMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.ChatMsg.class, Msg.ChatMsg.Builder.class);
      }

      // Construct using Msg.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        fromId_ = 0L;

        destId_ = 0L;

        createTime_ = 0L;

        step_ = 0;

        msgBody_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_ChatMsg_descriptor;
      }

      public Msg.ChatMsg getDefaultInstanceForType() {
        return Msg.ChatMsg.getDefaultInstance();
      }

      public Msg.ChatMsg build() {
        Msg.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.ChatMsg buildPartial() {
        Msg.ChatMsg result = new Msg.ChatMsg(this);
        result.id_ = id_;
        result.fromId_ = fromId_;
        result.destId_ = destId_;
        result.createTime_ = createTime_;
        result.step_ = step_;
        result.msgBody_ = msgBody_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.ChatMsg) {
          return mergeFrom((Msg.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.ChatMsg other) {
        if (other == Msg.ChatMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getDestId() != 0L) {
          setDestId(other.getDestId());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getStep() != 0) {
          setStep(other.getStep());
        }
        if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBody(other.getMsgBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long destId_ ;
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public long getDestId() {
        return destId_;
      }
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public Builder setDestId(long value) {
        
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public Builder clearDestId() {
        
        destId_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int step_ ;
      /**
       * <code>optional int32 step = 5;</code>
       */
      public int getStep() {
        return step_;
      }
      /**
       * <code>optional int32 step = 5;</code>
       */
      public Builder setStep(int value) {
        
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 step = 5;</code>
       */
      public Builder clearStep() {
        
        step_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:ChatMsg)
    private static final Msg.ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Msg.ChatMsg();
    }

    public static Msg.ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    public Msg.ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AckMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AckMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional uint64 fromId = 2;</code>
     */
    long getFromId();

    /**
     * <code>optional uint64 destId = 3;</code>
     */
    long getDestId();

    /**
     * <code>optional int32 msgType = 4;</code>
     */
    int getMsgType();

    /**
     * <code>optional int64 createTime = 5;</code>
     */
    long getCreateTime();

    /**
     * <code>optional int32 step = 6;</code>
     */
    int getStep();

    /**
     * <code>optional uint64 ackMsgId = 7;</code>
     */
    long getAckMsgId();
  }
  /**
   * Protobuf type {@code AckMsg}
   */
  public  static final class AckMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AckMsg)
      AckMsgOrBuilder {
    // Use AckMsg.newBuilder() to construct.
    private AckMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckMsg() {
      id_ = 0L;
      fromId_ = 0L;
      destId_ = 0L;
      msgType_ = 0;
      createTime_ = 0L;
      step_ = 0;
      ackMsgId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AckMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 16: {

              fromId_ = input.readUInt64();
              break;
            }
            case 24: {

              destId_ = input.readUInt64();
              break;
            }
            case 32: {

              msgType_ = input.readInt32();
              break;
            }
            case 40: {

              createTime_ = input.readInt64();
              break;
            }
            case 48: {

              step_ = input.readInt32();
              break;
            }
            case 56: {

              ackMsgId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_AckMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_AckMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.AckMsg.class, Msg.AckMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int FROMID_FIELD_NUMBER = 2;
    private long fromId_;
    /**
     * <code>optional uint64 fromId = 2;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int DESTID_FIELD_NUMBER = 3;
    private long destId_;
    /**
     * <code>optional uint64 destId = 3;</code>
     */
    public long getDestId() {
      return destId_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <code>optional int32 msgType = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 5;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int STEP_FIELD_NUMBER = 6;
    private int step_;
    /**
     * <code>optional int32 step = 6;</code>
     */
    public int getStep() {
      return step_;
    }

    public static final int ACKMSGID_FIELD_NUMBER = 7;
    private long ackMsgId_;
    /**
     * <code>optional uint64 ackMsgId = 7;</code>
     */
    public long getAckMsgId() {
      return ackMsgId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (fromId_ != 0L) {
        output.writeUInt64(2, fromId_);
      }
      if (destId_ != 0L) {
        output.writeUInt64(3, destId_);
      }
      if (msgType_ != 0) {
        output.writeInt32(4, msgType_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(5, createTime_);
      }
      if (step_ != 0) {
        output.writeInt32(6, step_);
      }
      if (ackMsgId_ != 0L) {
        output.writeUInt64(7, ackMsgId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fromId_);
      }
      if (destId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, destId_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, msgType_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      if (step_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, step_);
      }
      if (ackMsgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, ackMsgId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Msg.AckMsg)) {
        return super.equals(obj);
      }
      Msg.AckMsg other = (Msg.AckMsg) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getFromId()
          == other.getFromId());
      result = result && (getDestId()
          == other.getDestId());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getStep()
          == other.getStep());
      result = result && (getAckMsgId()
          == other.getAckMsgId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDestId());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + STEP_FIELD_NUMBER;
      hash = (53 * hash) + getStep();
      hash = (37 * hash) + ACKMSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAckMsgId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Msg.AckMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.AckMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.AckMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.AckMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.AckMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.AckMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.AckMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Msg.AckMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.AckMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.AckMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AckMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AckMsg)
        Msg.AckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_AckMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_AckMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.AckMsg.class, Msg.AckMsg.Builder.class);
      }

      // Construct using Msg.AckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        fromId_ = 0L;

        destId_ = 0L;

        msgType_ = 0;

        createTime_ = 0L;

        step_ = 0;

        ackMsgId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_AckMsg_descriptor;
      }

      public Msg.AckMsg getDefaultInstanceForType() {
        return Msg.AckMsg.getDefaultInstance();
      }

      public Msg.AckMsg build() {
        Msg.AckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.AckMsg buildPartial() {
        Msg.AckMsg result = new Msg.AckMsg(this);
        result.id_ = id_;
        result.fromId_ = fromId_;
        result.destId_ = destId_;
        result.msgType_ = msgType_;
        result.createTime_ = createTime_;
        result.step_ = step_;
        result.ackMsgId_ = ackMsgId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.AckMsg) {
          return mergeFrom((Msg.AckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.AckMsg other) {
        if (other == Msg.AckMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getDestId() != 0L) {
          setDestId(other.getDestId());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getStep() != 0) {
          setStep(other.getStep());
        }
        if (other.getAckMsgId() != 0L) {
          setAckMsgId(other.getAckMsgId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.AckMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.AckMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fromId = 2;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long destId_ ;
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public long getDestId() {
        return destId_;
      }
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public Builder setDestId(long value) {
        
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 destId = 3;</code>
       */
      public Builder clearDestId() {
        
        destId_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>optional int32 msgType = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional int32 msgType = 4;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgType = 4;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 5;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 5;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 5;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int step_ ;
      /**
       * <code>optional int32 step = 6;</code>
       */
      public int getStep() {
        return step_;
      }
      /**
       * <code>optional int32 step = 6;</code>
       */
      public Builder setStep(int value) {
        
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 step = 6;</code>
       */
      public Builder clearStep() {
        
        step_ = 0;
        onChanged();
        return this;
      }

      private long ackMsgId_ ;
      /**
       * <code>optional uint64 ackMsgId = 7;</code>
       */
      public long getAckMsgId() {
        return ackMsgId_;
      }
      /**
       * <code>optional uint64 ackMsgId = 7;</code>
       */
      public Builder setAckMsgId(long value) {
        
        ackMsgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ackMsgId = 7;</code>
       */
      public Builder clearAckMsgId() {
        
        ackMsgId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AckMsg)
    }

    // @@protoc_insertion_point(class_scope:AckMsg)
    private static final Msg.AckMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Msg.AckMsg();
    }

    public static Msg.AckMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckMsg>
        PARSER = new com.google.protobuf.AbstractParser<AckMsg>() {
      public AckMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AckMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckMsg> getParserForType() {
      return PARSER;
    }

    public Msg.AckMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 源目标模块类型
     * </pre>
     *
     * <code>optional int32 from = 2;</code>
     */
    int getFrom();

    /**
     * <pre>
     * 目标模块类型
     * </pre>
     *
     * <code>optional int32 dest = 3;</code>
     */
    int getDest();

    /**
     * <code>optional int64 createTime = 4;</code>
     */
    long getCreateTime();

    /**
     * <code>optional int32 msgType = 5;</code>
     */
    int getMsgType();

    /**
     * <code>optional bytes msgBody = 6;</code>
     */
    com.google.protobuf.ByteString getMsgBody();
  }
  /**
   * Protobuf type {@code InternalMsg}
   */
  public  static final class InternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InternalMsg)
      InternalMsgOrBuilder {
    // Use InternalMsg.newBuilder() to construct.
    private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMsg() {
      id_ = 0L;
      from_ = 0;
      dest_ = 0;
      createTime_ = 0L;
      msgType_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 16: {

              from_ = input.readInt32();
              break;
            }
            case 24: {

              dest_ = input.readInt32();
              break;
            }
            case 32: {

              createTime_ = input.readInt64();
              break;
            }
            case 40: {

              msgType_ = input.readInt32();
              break;
            }
            case 50: {

              msgBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_InternalMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.InternalMsg.class, Msg.InternalMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private int from_;
    /**
     * <pre>
     * 源目标模块类型
     * </pre>
     *
     * <code>optional int32 from = 2;</code>
     */
    public int getFrom() {
      return from_;
    }

    public static final int DEST_FIELD_NUMBER = 3;
    private int dest_;
    /**
     * <pre>
     * 目标模块类型
     * </pre>
     *
     * <code>optional int32 dest = 3;</code>
     */
    public int getDest() {
      return dest_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <code>optional int32 msgType = 5;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>optional bytes msgBody = 6;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (from_ != 0) {
        output.writeInt32(2, from_);
      }
      if (dest_ != 0) {
        output.writeInt32(3, dest_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(4, createTime_);
      }
      if (msgType_ != 0) {
        output.writeInt32(5, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        output.writeBytes(6, msgBody_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, from_);
      }
      if (dest_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dest_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, msgBody_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Msg.InternalMsg)) {
        return super.equals(obj);
      }
      Msg.InternalMsg other = (Msg.InternalMsg) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getFrom()
          == other.getFrom());
      result = result && (getDest()
          == other.getDest());
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && getMsgBody()
          .equals(other.getMsgBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + DEST_FIELD_NUMBER;
      hash = (53 * hash) + getDest();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Msg.InternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.InternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.InternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.InternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.InternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.InternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.InternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Msg.InternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Msg.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Msg.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Msg.InternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InternalMsg)
        Msg.InternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_InternalMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_InternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.InternalMsg.class, Msg.InternalMsg.Builder.class);
      }

      // Construct using Msg.InternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        from_ = 0;

        dest_ = 0;

        createTime_ = 0L;

        msgType_ = 0;

        msgBody_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_InternalMsg_descriptor;
      }

      public Msg.InternalMsg getDefaultInstanceForType() {
        return Msg.InternalMsg.getDefaultInstance();
      }

      public Msg.InternalMsg build() {
        Msg.InternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.InternalMsg buildPartial() {
        Msg.InternalMsg result = new Msg.InternalMsg(this);
        result.id_ = id_;
        result.from_ = from_;
        result.dest_ = dest_;
        result.createTime_ = createTime_;
        result.msgType_ = msgType_;
        result.msgBody_ = msgBody_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.InternalMsg) {
          return mergeFrom((Msg.InternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.InternalMsg other) {
        if (other == Msg.InternalMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getDest() != 0) {
          setDest(other.getDest());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBody(other.getMsgBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.InternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.InternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int from_ ;
      /**
       * <pre>
       * 源目标模块类型
       * </pre>
       *
       * <code>optional int32 from = 2;</code>
       */
      public int getFrom() {
        return from_;
      }
      /**
       * <pre>
       * 源目标模块类型
       * </pre>
       *
       * <code>optional int32 from = 2;</code>
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 源目标模块类型
       * </pre>
       *
       * <code>optional int32 from = 2;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int dest_ ;
      /**
       * <pre>
       * 目标模块类型
       * </pre>
       *
       * <code>optional int32 dest = 3;</code>
       */
      public int getDest() {
        return dest_;
      }
      /**
       * <pre>
       * 目标模块类型
       * </pre>
       *
       * <code>optional int32 dest = 3;</code>
       */
      public Builder setDest(int value) {
        
        dest_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标模块类型
       * </pre>
       *
       * <code>optional int32 dest = 3;</code>
       */
      public Builder clearDest() {
        
        dest_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>optional int32 msgType = 5;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional int32 msgType = 5;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgType = 5;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msgBody = 6;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:InternalMsg)
    }

    // @@protoc_insertion_point(class_scope:InternalMsg)
    private static final Msg.InternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Msg.InternalMsg();
    }

    public static Msg.InternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
      public InternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalMsg> getParserForType() {
      return PARSER;
    }

    public Msg.InternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InternalMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"h\n\007ChatMsg\022\n\n\002id\030\001 \001(\004\022\016" +
      "\n\006fromId\030\002 \001(\004\022\016\n\006destId\030\003 \001(\004\022\022\n\ncreate" +
      "Time\030\004 \001(\003\022\014\n\004step\030\005 \001(\005\022\017\n\007msgBody\030\006 \001(" +
      "\014\"y\n\006AckMsg\022\n\n\002id\030\001 \001(\004\022\016\n\006fromId\030\002 \001(\004\022" +
      "\016\n\006destId\030\003 \001(\004\022\017\n\007msgType\030\004 \001(\005\022\022\n\ncrea" +
      "teTime\030\005 \001(\003\022\014\n\004step\030\006 \001(\005\022\020\n\010ackMsgId\030\007" +
      " \001(\004\"k\n\013InternalMsg\022\n\n\002id\030\001 \001(\004\022\014\n\004from\030" +
      "\002 \001(\005\022\014\n\004dest\030\003 \001(\005\022\022\n\ncreateTime\030\004 \001(\003\022" +
      "\017\n\007msgType\030\005 \001(\005\022\017\n\007msgBody\030\006 \001(\014B\005B\003Msg" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMsg_descriptor,
        new java.lang.String[] { "Id", "FromId", "DestId", "CreateTime", "Step", "MsgBody", });
    internal_static_AckMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AckMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckMsg_descriptor,
        new java.lang.String[] { "Id", "FromId", "DestId", "MsgType", "CreateTime", "Step", "AckMsgId", });
    internal_static_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InternalMsg_descriptor,
        new java.lang.String[] { "Id", "From", "Dest", "CreateTime", "MsgType", "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
