redis:
  host: localhost
  port: 6379
  lock:
    expire: 100


msgid:
  increase_step: 100


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: qwer1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml