redis:
  host: localhost
  port: 6379
  lock:
    expire: 100

server:
  port: 8088


msgid:
  increase_step: 100


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haha_im
    username: root
    password: qwer1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml


user_msg_id:
  next_id_impl: memory